### ISSUE TITLE
Citing verifyTrusty

### ISSUE THREAD

**Issue by shaobo-he** [agurfinkel/verifyTrusty#2]
Hello,

May I ask if there's a paper that describes the work done in this repo?

**Comment by agurfinkel** [comment]
https://arxiv.org/abs/2107.00723

to appear in ATVA 2021

**Comment by shaobo-he** [comment]
> https://arxiv.org/abs/2107.00723
> 
> to appear in ATVA 2021

Thank you Arie. However, I didn't find anything related to TEE in the paper you sent.

**Comment by agurfinkel** [comment]
oops, wrong reference. I got lost in our repositories. No, there is nothing written in verifyTrusty yet. This is active work in progress. Sorry for the confusion.
